version: '3.8'

services:
  web:
    build: .
    container_name: game-lobby-web
    restart: always
    ports:
      - "9080:9080"
      - "9443:9443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${SSL_EMAIL} -d ${DOMAIN} --agree-tos
    depends_on:
      - web

networks:
  app-network:
    driver: bridge