# version: '3.8'

services:
  web:
    build: .
    container_name: game-lobby-web
    restart: unless-stopped
    ports:
      - "9080:9080"
      - "9443:9443"
    volumes:
      - ./config/nginx/ssl.conf:/etc/nginx/ssl/ssl.conf:ro
    networks:
      - app-network
    environment:
      - DOMAIN=${DOMAIN:-localhost}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9080"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge
