# version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d/play.conf:/etc/nginx/conf.d/play.conf:ro
      - /etc/nginx/ssl/play.saga4v.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/nginx/ssl/play.saga4v.com/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    depends_on:
      frontend:
        condition: service_healthy
    networks:
      - app_network
    restart: unless-stopped

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=5173
      - VITE_USE_HTTPS=true
      # Firebase Config
      - VITE_FIREBASE_API_KEY
      - VITE_FIREBASE_AUTH_DOMAIN
      - VITE_FIREBASE_PROJECT_ID
      - VITE_FIREBASE_STORAGE_BUCKET
      - VITE_FIREBASE_MESSAGING_SENDER_ID
      - VITE_FIREBASE_APP_ID
      - VITE_FIREBASE_MEASUREMENT_ID
      - VITE_FIREBASE_DYNAMIC_LINK_DOMAIN
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

networks:
  app_network:
    driver: bridge 